# Generated by Django 2.2.6 on 2019-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=150)),
                ('date_and_time_published', models.DateTimeField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
