# Generated by Django 2.2.6 on 2019-10-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_and_time_published',
            new_name='date_published',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
