# Generated by Django 2.2.6 on 2019-10-19 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191017_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
