# Generated by Django 2.2.6 on 2019-10-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_registration',
            new_name='registration_date',
        ),
    ]
