# Generated by Django 2.2.6 on 2019-10-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191017_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
    ]
