# Generated by Django 2.2.6 on 2019-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='token', max_length=200),
            preserve_default=False,
        ),
    ]
